export const products = [
  {
    image: "./assets/img/1.webp",
    hiddenImage: "./ ,",
    heartIconFavorites: "&hearts;",
    percentSale: "-50%",
    typeDescription: "Sostenibilità",
    brand: "levi's",
    name: "Relaxed Fit Tee UNISEX",
    originalPrice: "29.99€",
    finalPrice: "14.99€",
  },
  {
    image: "./assets/img/2.webp",
    hiddenImage: "./ ,",
    heartIconFavorites: "&hearts;",
    percentSale: "-50%",
    typeDescription: "Sostenibilità",
    brand: "levi's",
    name: "Relaxed Fit Tee UNISEX",
    originalPrice: "29.99€",
    finalPrice: "14.99€",
  },
  {
    image: "./assets/img/3.webp",
    hiddenImage: "./ ,",
    heartIconFavorites: "&hearts;",
    percentSale: "-50%",
    typeDescription: "Sostenibilità",
    brand: "levi's",
    name: "Relaxed Fit Tee UNISEX",
    originalPrice: "29.99€",
    finalPrice: "14.99€",
  },
  {
    image: "./assets/img/4.webp",
    hiddenImage: "./ ,",
    heartIconFavorites: "&hearts;",
    percentSale: "-50%",
    typeDescription: "Sostenibilità",
    brand: "levi's",
    name: "Relaxed Fit Tee UNISEX",
    originalPrice: "29.99€",
    finalPrice: "14.99€",
  },
  {
    image: "./assets/img/5.webp",
    hiddenImage: "./ ,",
    heartIconFavorites: "&hearts;",
    percentSale: "-50%",
    typeDescription: "Sostenibilità",
    brand: "levi's",
    name: "Relaxed Fit Tee UNISEX",
    originalPrice: "29.99€",
    finalPrice: "14.99€",
  },
  {
    image: "./assets/img/6.webp",
    hiddenImage: "./ ,",
    heartIconFavorites: "&hearts;",
    percentSale: "-50%",
    typeDescription: "Sostenibilità",
    brand: "levi's",
    name: "Relaxed Fit Tee UNISEX",
    originalPrice: "29.99€",
    finalPrice: "14.99€",
  },
];
