export const products = [
  {
    image: "/1.webp",
    hiddenImage: "/1b.webp ",
    heartIconFavorites: "&hearts;",
    percentSale: "-50%",
    typeDescription: "Sostenibilità",
    brand: "levi's",
    name: "Relaxed Fit Tee UNISEX",
    originalPrice: "29.99€",
    finalPrice: "14.99€",
  },
  {
    image: "/2.webp",
    hiddenImage: "/2b.webp ",
    heartIconFavorites: "&hearts;",
    percentSale: "-50%",
    typeDescription: "Sostenibilità",
    brand: "levi's",
    name: "Relaxed Fit Tee UNISEX",
    originalPrice: "29.99€",
    finalPrice: "14.99€",
  },
  {
    image: "/3.webp",
    hiddenImage: "/3b.webp",
    heartIconFavorites: "&hearts;",
    percentSale: "-50%",
    typeDescription: "Sostenibilità",
    brand: "levi's",
    name: "Relaxed Fit Tee UNISEX",
    originalPrice: "29.99€",
    finalPrice: "14.99€",
  },
  {
    image: "/4.webp",
    hiddenImage: "/4b.webp",
    heartIconFavorites: "&hearts;",
    percentSale: "-50%",
    typeDescription: "Sostenibilità",
    brand: "levi's",
    name: "Relaxed Fit Tee UNISEX",
    originalPrice: "29.99€",
    finalPrice: "14.99€",
  },
  {
    image: "/5.webp",
    hiddenImage: "/5b.webp ",
    heartIconFavorites: "&hearts;",
    percentSale: "-50%",
    typeDescription: "Sostenibilità",
    brand: "levi's",
    name: "Relaxed Fit Tee UNISEX",
    originalPrice: "29.99€",
    finalPrice: "14.99€",
  },
  {
    image: "/6.webp",
    hiddenImage: "/6b.webp",
    heartIconFavorites: "&hearts;",
    percentSale: "-50%",
    typeDescription: "Sostenibilità",
    brand: "levi's",
    name: "Relaxed Fit Tee UNISEX",
    originalPrice: "29.99€",
    finalPrice: "14.99€",
  },
];
